<?php
$this->title = "Add new album";
$this->headTitle($this->title);
?>

<form class="form-signin" method="post" action="">
  <h2 class="form-signin-heading">Please add artist</h2>
  <input type="text" class="form-control" placeholder="Artist Name" name="artist" autofocus>
  <input type="text" class="form-control" placeholder="Title" name="title">
  <button class="btn btn-lg btn-primary btn-block" type="submit">Add Artist</button>
</form>

