<?php
$this->title = "Edit album";
$this->headTitle($this->title);
?>


<form id="album"  action="" method="post">
  <dl class="zend_form">

    <dt id="id-label">&#160;</dt>
    <dd id="id-element">
      <input type="hidden" name="id" value="<?=$this->id?>" id="id" />
    </dd>

    <dt id="artist-label">
    <label for="artist" class="required">
    Artist</label></dt>
    <dd id="artist-element">
    <input type="text" name="artist" id="artist" value="<?=$this->album['artist']?>" /></dd>

    <dt id="title-label"><label for="title" class="required">Title</label></dt>
    <dd id="title-element"><input type="text" name="title" id="title" value="<?=$this->album['title']?>" /></dd>

    <dt id="submit-label">&#160;</dt>
    <dd id="submit-element"><input type="submit" name="submit" id="submitbutton" value="I am done" /></dd>
  </dl>
</form>
