<h4>
  My Albums
</h4>
<table class="table table-hover table-bordered">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->ratnesh as $album) : ?>
<tr>
    <td><?php echo $this->escape($album->title);?></td>
    <td><?php echo $this->escape($album->artist);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'index',
            'action'=>'edit', 'id'=>$album->id));?>"><span class="glyphicon glyphicon-edit"></span></a>
        <a href="<?php echo $this->url(array('controller'=>'index',
            'action'=>'delete', 'id'=>$album->id));?>"><span class="glyphicon glyphicon-trash"></span></a>
    </td>
</tr>
<?php endforeach; ?>
</table>
