  <?php if(isset($this->loginMessage)){ ?>
   <span class="error"><?php echo $this->loginMessage; ?></span>
  <?php }?>

 <form class="form-signin" method="post">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" class="form-control" name="email" placeholder="Email address" autofocus>
        <input type="password" name="password" class="form-control" placeholder="Password">
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
<br>
  <a href="<?php echo $this->url(array('action'=>'register')); ?>">Create Account</a>

      </form>



