 
 <form class="form-signin" method="post">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" class="form-control" name="email" placeholder="Email address is .." autofocus>
        <input type="password" name="password" class="form-control" placeholder="Password is..">
        <input type="text" name="name" class="form-control" placeholder="My name is..">
        
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Register Me</button>
<br>

      </form>



